name       : toluapp
version    : 1.0.93
release    : 4
source     :
    - https://github.com/LuaDist/toluapp/archive/1.0.93.tar.gz : 0a1ff87cb74e7531aec57e2a7cfdf282116647dea3b46223e3cc7c362b55b5bb
component  : programming.tools
license    : MIT
summary    : tolua++ is an extension of toLua, a tool to integrate C/Cpp code with Lua
description: |
    tolua is a tool that greatly simplifies the integration of C/C++ code with Lua. Based on a "cleaned" header file, tolua automatically generates the binding code to access C/C++ features from Lua. Using Lua-5.0 API and metamethod facilities, the current version automatically maps C/C++ constants, external variables, functions, namespace, classes, and methods to Lua. It also provides facilities to create Lua modules.
builddeps  :
    - pkgconfig(lua-5.1)
libsplit   : no
patterns   :
    - devel :
        - /usr/bin
        - /usr/share/toluapp
setup      : |
    %patch -p1 < $pkgfiles/0001-Fix-reference-to-lua-5.1.patch
    %cmake . -DCMAKE_INSTALL_PREFIX=/usr
build      : |
    %make
install    : |
    %make_install
